---
- name: Installing and configuring docker
  hosts: all
  remote_user: root
  become: true
  gather_facts: true
  roles:
    - { role: roles/rancher-docker }

- name: Installing and configuring HA postgresql cluster
  hosts: postgresql_cluster
  remote_user: root
  become: true
  gather_facts: true
  roles:
    - { role: roles/postgresql }

- name: Installing and configuring mongodb replicaset cluster
  hosts: mongodb_cluster
  remote_user: root
  become: true
  gather_facts: true
  roles:
    - { role: roles/mongodb }

- name: Installing and configuring zabbix server in docker
  hosts: zabbix_docker
  remote_user: root
  become: true
  gather_facts: true
  roles:
    - { role: roles/zabbix-docker }
